export const ON_FETCH_DATA = "ON_FETCH_DATA";
export const ON_FETCH_DATA_SUCCESS = "ON_FETCH_DATA_SUCCESS";
export const ON_FETCH_DATA_FAIL = "ON_FETCH_DATA_FAIL";
export const ON_CLEAR_DATA = "ON_CLEAR_DATA";

export const SEND_ANSWERS = "SEND_ANSWERS";

export const ON_CLEAR_SEND_DATA = "ON_CLEAR_SEND_DATA";
export const ON_SEND_PRACTICE = "ON_SEND_PRACTICE";
export const ON_SEND_PRACTICE_SUCCESS = "ON_SEND_PRACTICE_SUCCESS";
export const ON_SEND_PRACTICE_FAIL = "ON_SEND_PRACTICE_FAIL";

export const ON_GET_TITLE = "ON_GET_TITLE";
export const ON_GET_TITLE_SUCCESS = "ON_GET_TITLE_SUCCESS";
export const ON_GET_TITLE_FAIL = "ON_GET_TITLE_FAIL";
