export const ON_FETCH_DATA = "ON_FETCH_DATA";
export const ON_FETCH_DATA_SUCCESS = "ON_FETCH_DATA_SUCCESS";
export const ON_FETCH_DATA_FAIL = "ON_FETCH_DATA_FAIL";
export const ON_CLEAR_DATA = "ON_CLEAR_DATA";

export const SEND_ANSWERS = "SEND_ANSWERS";